format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$line_break\
$character"""

[directory]
style = "#D19C97"

[character]
success_symbol = "[■](#F0E9E0)"
error_symbol = "[■](#d19c97)"
vimcmd_symbol = "[𝓥](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#D19C97) ($ahead_behind$stashed)]($style) "
style = "#A47764"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
disabled = true

[kubernetes]
style = "blue"
disabled = false
symbol = "k◼ "
format = '[$symbol$context (⸢$namespace⸥)]($style)'
detect_env_vars = ["KUBECONFIG"]
