show_raw_agent_reasoning = false
hide_agent_reasoning = false
model = "gpt-5.4"
model_reasoning_effort = "high"
web_search = "live"

approval_policy = "on-request"
sandbox_mode = "workspace-write"
personality = "pragmatic"
suppress_unstable_features_warning = true
approvals_reviewer = "guardian_subagent"

[shell_environment_policy]
inherit = "all"

[features]
apply_patch_freeform = true
shell_snapshot = true
unified_exec = true
steer = true
multi_agent = true
js_repl = true
prevent_idle_sleep = true
voice_transcription = true
guardian_approval = true

[tui]
notifications = true
status_line = [
  "model-with-reasoning",
  "context-remaining",
  "current-dir",
  "git-branch",
  "total-output-tokens",
]


[sandbox_workspace_write]
exclude_tmpdir_env_var = false                                     # Allow $TMPDIR
exclude_slash_tmp = false                                          # Allow /tmp
writable_roots = ["/Users/zilizhang/.codex", "/Users/zili/.codex"]
network_access = true                                              # Opt in to outbound network

[projects."/Users/zilizhang"]
trust_level = "trusted"

[projects."/Users/zilizhang/code"]
trust_level = "trusted"

[projects."/Users/zilizhang/tmp"]
trust_level = "trusted"

[projects."/Users/zilizhang/.codex"]
trust_level = "trusted"

[projects."/Users/zilizhang/Downloads"]
trust_level = "untrusted"

[projects."/Users/zili"]
trust_level = "trusted"

[projects."/Users/zili/code"]
trust_level = "trusted"

[projects."/Users/zili/tmp"]
trust_level = "trusted"

[projects."/Users/zili/.codex"]
trust_level = "trusted"

[projects."/Users/zili/Downloads"]
trust_level = "untrusted"

[projects."/Users/zili/.dotfiles"]
trust_level = "trusted"

[projects."/Users/zili/code/eargo-worktrees/eargo"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/tries"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/sre/skills"]
trust_level = "trusted"

[projects."/Users/zilizhang/.dotfiles"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/sre/helmist"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/codeet"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/zmk-config-fire"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/zmk-config-v3"]
trust_level = "trusted"

[projects."/Users/zilizhang/tmp/datakit"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/sre/rr"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/notex"]
trust_level = "trusted"

[projects."/Users/zilizhang/code/eargo-worktrees/eargo"]
trust_level = "trusted"

[projects."/Users/zili/code/resume"]
trust_level = "trusted"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[[skills.config]]
path = "~/.agents/skills/agent-browser/SKILL.md"
enabled = true

[mcp_servers.paper]
enabled = false
url = "http://127.0.0.1:29979/mcp"
