set -g mouse on

# fast reload tmux config file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# remap prefix to Control + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Start windows and panes at 1, not 0 set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift Alt vim keys to switch windows
bind -n M-, previous-window
bind -n M-. next-window

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Vim style pane selection
# we usually use 'Ctrl + h,j,k,l' to switch pane (powered by the plugin 'christoomey/vim-tmux-navigator')
# but if we are in a vim/nvim/vi buffer, we can't use that
# so the following 4 bindings allow us to use <prefix> + h,j,k,l to switch pane even when we are in a vim buffer
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

# Create new pane in the same CWD
unbind 's'
bind 's' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"

# Keybinding for Copy Mode and tmux-yank
# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g default-terminal "screen-256color"

# # active window status bar highlight
# set-window-option -g window-status-current-style fg=colour235
# set-window-option -g window-status-current-style bg=colour240
# set-window-option -g window-status-style fg=colour244
# set-window-option -g window-status-style bg=default

# # set bottom status bar color
# set -g status-bg colour235
# set -g status-fg colour181

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# the tmux-resurrect pulgin
run-shell ~/clone/path/resurrect.tmux

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

